export const FETCH_PRODUCTS = 'app/FETCH_PRODUCTS';
export const FETCH_CATEGORIES = 'app/FETCH_CATEGORIES';
export const SELECT_CATEGORY = 'app/SELECT_CATEGORY';
export const SEARCH_KEYWORD = 'app/SEARCH_KEYWORD';